fix(build): Enable Docker BuildKit in build_images.sh
Enable Docker BuildKit for improved build performance.
解决镜像构建报错:
```
RUN --mount=type=cache,target=/go/pkg/mod go mod download
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
```
设置开启buildx后, 脚本运行会提前报错:
```
ERROR: BuildKit is enabled but the buildx component is missing or broken.
       Install the buildx component to build images with BuildKit:
       https://docs.docker.com/go/buildx/
```